=== JikesRVM/JikesRVM/kenan/conf/config.dtd
<!ELEMENT configuration (entry+)>
<!ELEMENT entry (key,(value | list))>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT list (value+ | subentry+)>
<!ELEMENT subentry (key,value+)>

=== JikesRVM/JikesRVM/kenan/conf/config.xml
<!--<!DOCTYPE configuration SYSTEM "config.dtd">-->
<!-- to developers: have a look at the config.dtd to 
     see how to structure your config entries -->

<configuration>
  <entry>
    <key>version</key>
    <value>FOP 0.20.5</value>
  </entry>

  <!-- default values for commandline options -->
  <!-- suppress all progress information, error message are still displayed -->
  <entry>
    <key>quiet</key>
    <value>false</value>
  </entry>
<!-- sets debug mode on/off; debug mode hasm more progress 
     information and a stacktrace in case of a fatal exception -->
  <entry>
    <key>debugMode</key>
    <value>false</value>
  </entry>
  <!-- displays all configuration  settings and then exits -->
  <entry>
    <key>dumpConfiguration</key>
    <value>false</value>
  </entry>

  <!-- stream-filter-list provides the default filters that are applied to all
       stream objects within the PDF file. These are normally used for 
       compression -->
  <entry role="pdf">
    <key>stream-filter-list</key>
    <list>
      <!-- provides compression using zlib flate (default is on)-->
      <value>flate</value>
      
      <!-- encodes binary data into printable ascii characters (default off)
           This provides about a 4:5 expansion of data size -->
      <value>ascii-85</value>

      <!-- encodes binary data with hex representation (default off)
           This filter is not recommended as it doubles the data size -->
      <!-- <value>ascii-hex</value> -->
    </list>
  </entry>
  <fonts>
  </fonts>
</configuration>
